stages:
  - test
  - build

realizar_testes:
  stage: test
  image: node:20.7.0-alpine3.17
  before_script:
    - cd app/
    - npm install
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml

build-images:
  stage: build
  needs:
    - realizar_testes
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - echo $REGISTRY_USER
    - echo $REGISTRY_PASS_HUB
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS_HUB

  script:
    - docker build -t victorbruno221/gitlab-cicd-node:1.0 .
    - docker push victorbruno221/gitlab-cicd-node:1.0
